version: 2.1

orbs:
  auto: artsy/auto@1.3.2
  node: artsy/node@1.0.0
  yarn: artsy/yarn@5.1.3

workflows:
  default:
    jobs:
      - yarn/update-cache
      - yarn/lint
      - yarn/test
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/lint
            - yarn/test
