version: 2.1

orbs:
  yarn: artsy/yarn@2.1.0

workflows:
  default:
    jobs:
      - yarn/update-cache
      - yarn/test
      - yarn/auto-release:
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/test
